name: altaa
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '45432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Interface Web

  api:
    build: ./backend
    env_file:
      - .env
    environment:
      NODE_ENV: ${ENV}
      PORT: ${BACKEND_PORT}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_SAME_SITE: ${COOKIE_SAME_SITE}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3003:3001"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: "${API_URL}"
    ports:
      - '3002:3000'
    environment:
      NEXT_PUBLIC_API_URL: "${API_URL}"
    depends_on:
      - api

volumes:
  pgdata:
